[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "my-cli"
version = "0.1.0"
authors = [
  { name="Your Name", email="you@example.com" },
]
description = "CLI Tool Description"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[project.scripts]
my-cli = "my_cli.cli:main"

[tool.setuptools.packages.find]
where = ["src"]